---
title: "Convex Clustering Example"
author: "D2K Course Staff"
date: "`r format(Sys.time(), '%B %d %Y')`"
output: pdf_document
---

```{r setup, include=FALSE}
library(knitr) # We need the knitr package to set chunk options
library(tidyverse)

# Set default knitr options for knitting code into the report:
opts_chunk$set(echo=TRUE,  # change to FALSE to keep code out of the knitted document
               cache=FALSE, # re-run code that has already been run?
               autodep=TRUE, # assure that caching dependencies are updated correctly
               cache.comments=FALSE, # do not re-run a chunk if only comments are changed
               message=FALSE, # change to FALSE to keep messages out of the knitted document
               warning=FALSE,  # change to FALSE to keep warnings out of the knitted document
               comment = NA,
               tidy.opts=list(width.cutoff=65),
               fig.height = 3.5)

theme1 <- theme_bw() +
  theme(axis.text = element_text(size = 8, colour = "#6b3447"),
        axis.title = element_text(size = 10, colour = "#2f2f63"),
        legend.title = element_text(size = 8, colour = "#2f2f63"),
        legend.text = element_text(size = 8, colour = "#6b3447"), 
        title = element_text(size = 12, colour = "#2f2f63"), 
        axis.ticks = element_line(colour = "#6b3447"),
        plot.caption = element_text(size = 8, colour = "#2f2f63"),
        plot.subtitle = element_text(size = 10, colour = "#2f2f63"))
```

# Introduction

One of them newfangled clustering methods that all the cool stat ids are using these days is called convex clustering. The basic idea is to minimize the sum of the distances between each of the observations and their assigned cluster centroid and the distances between each of the assigned cluster centroids. This can be thought of as something like a ridge or LASSO problem for clustering.  

Formally, define our data matrix as $\textbf{X}$ with $i \in 1, ..., m$ rows of observations and $j \in 1, ..., n$ columns. We then want to find the corresponding cluster centroid matrix $\textbf{U}$, also with $i \in 1, ..., m$ rows and $j \in 1, ..., n$ columns, that minimizes $$\frac{1}{2} \sum_{i = 1}^m \|\textbf{X}_i - \textbf{U}_i\|_2 + \gamma \sum_{k < l} w_{kl} \|\textbf{U}_k - \textbf{U}_l\|_2.$$ In the above, $\textbf{U}_i$ is the centroid that corresponds to $\textbf{X}_i$ (not necessarily unique) and $\|.\|_2$ is your typical Euclidean distance. $w_{kl}$ is the weight that we give to each centroid pairing distance term - in general, this is calculated such that pairs of observations of $\textbf{X}_i$ that are further away have smaller weights (intuitively, we care less about fusing cluster centroids for points that are far apart compared to points that are close to each other.) $\gamma$ is the regularization parameter than controls the balance of the trade-off between the two summation terms. In the same way that the LASSO regulaization parameter pulls each coefficient toward 0, the convex clustering regularization parameter fuses the cluster centroids together toward the same point.

This has a few advantages over your basic clustering techniques:


1. The optimization problem has a unique solution for each given value of $\gamma$ and can be implemented via known convex opimization algorithms. This also allows us to choose the number of cluster centroids in a data-driven manner by setting $\gamma$ such that the solution gives the desired number of unique centroids.
2. We get an intuitive solution to changing the number of cluster centroids - decreasing the number of clusters fuses separate clusters together and increasing the number of clusters splits clusters apart. (Compare thta to k-means in the basic clustering example.)
3. We can create a regularization path, akin to ridge or LASSO regression to see how clusters fuse or split apart as we decrease or increase the number of clusters.



\newpage

# Implementation

There are a couple of R package implementations for convex clustering, `cvxclustr` and `cclust`. See which one works best for you. Read the CRAN reference for these for more details.

## No Examples?

Sorry. We're trying to find a good, simple example that gives an intuitive answer. For now, use the examples in the corresponding R package references.
